dist: bionic
language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  - sudo apt install clang-format
  - sudo apt install clang-tidy
  - sudo apt install cppcheck
  - sudo apt install valgrind
script:
  - cmake CMakeLists.txt
  - make